require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - "bin/**/*"
    - "config/**/*"
    - "db/**/*"
    - "node_modules/**/*"
    - "script/**/*"
    - "spec/rails_helper.rb"
    - "vendor/**/*"

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ["describe", "context", "feature", "scenario", "let", "it"]
