name: Running Code Coverage

on: [push, pull_request]

jobs:
  rspec-test:
    name: RSpec
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
          yarn install
      - name: Setup application
        run: bundle exec rails bin/setup
      - name: Create database
        run: |
          bundler exec rails db:create RAILS_ENV=test
          bundler exec rails db:migrate RAILS_ENV=test
      - name: Run tests
        run: bundle exec rake
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1